apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-pspd
  namespace: trab-pspd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-pspd
  template:
    metadata:
      labels:
        app: react-pspd
    spec:
      containers:
        - name: react-pspd
          image: lamequesao/react-trab-pspd  # Substitua com a imagem do seu frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_API_URL
              value: "http://fastapi-pspd-service:8000"
---
apiVersion: v1
kind: Service
metadata:
  name: react-pspd-service
  namespace: trab-pspd
spec:
  type: NodePort
  selector:
    app: react-pspd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
