version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: fastapi-backend
    environment:
      user: user
      password: password
      host: postgres-db
      port: 5432
      dbname: dbname
      # - DATABASE_URL=postgresql://user:password@db:5432/dbname
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: react-frontend
    environment:
      - REACT_APP_API_URL=http://backend:8000
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    networks:
      - app-network

  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
