# Imagem base para o React
FROM node:18

# Definir diretório de trabalho
WORKDIR /app

# Copiar package.json e package-lock.json (ou yarn.lock) para o container
COPY package*.json ./

# Instalar dependências
RUN npm install

# Copiar o restante do código
COPY . .

# Expor a porta que o React usará
EXPOSE 3000

# Comando para rodar o frontend React
CMD ["npm", "start"]
